name: Test and Deploy
env:
  PUBLISH_DIR: Nodexr/bin/Release/net6.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test -c Release --no-restore

    - name: Publish app
      run: dotnet publish -c Release --no-restore

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
